export type LookCategory = 'alpha-man' | 'suits' | 'accessories' | 'watches' | 'pocket-squares'

export interface Look {
  id: string
  title: string
  category: LookCategory
  description: string
  image: string
  aspectRatio: 'portrait' | 'landscape' | 'square'
  fabric: string
  craftsmanship: string
  care: string
}

export const LOOKS: Look[] = [
  {
    id: 'am-01',
    title: 'The Meridian',
    category: 'alpha-man',
    description: 'A dark navy two-piece cut to precision. The suit that defines the room before you speak.',
    image: 'https://images.unsplash.com/photo-1617137968427-85924c800a22?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: 'Super 120s Merino Wool, Loro Piana cloth',
    craftsmanship: 'Full canvas construction, hand-padded chest, surgeon\'s cuffs with working buttonholes',
    care: 'Dry clean only. Steam to refresh between wears. Store on a cedar shoulder hanger.',
  },
  {
    id: 'am-02',
    title: 'The Executive',
    category: 'alpha-man',
    description: 'Charcoal wool, single-breasted. Authority woven into every thread.',
    image: 'https://images.unsplash.com/photo-1598032895397-b9472444bf93?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: 'Super 130s Wool, Holland & Sherry English mill',
    craftsmanship: 'Half canvas, floating chest piece, pick-stitched lapels, hand-finished jetted pockets',
    care: 'Dry clean after 5–6 wears. Brush with a soft bristle brush after each wear.',
  },
  {
    id: 'am-03',
    title: 'The Accra Edit',
    category: 'alpha-man',
    description: 'Modern tailoring for the contemporary Ghanaian professional. Sharp. Intentional. Unmistakable.',
    image: 'https://images.unsplash.com/photo-1594938298603-5a883c20f36d?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: '150s Wool Mohair blend, Scabal cloth, lightweight for tropical climate',
    craftsmanship: 'Full canvas, structured shoulder, double-vented back, mother-of-pearl buttons',
    care: 'Dry clean only. Hang to air for 24 hours after wear before storing.',
  },
  {
    id: 'su-01',
    title: 'The Obsidian',
    category: 'suits',
    description: 'Midnight black with a subtle herringbone weave. The formal suit reimagined.',
    image: 'https://images.unsplash.com/photo-1507679799987-c73779587ccf?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: 'Super 120s Wool, Italian mill, fine herringbone weave',
    craftsmanship: 'Full canvas chest, hand-stitched buttonholes, single-button stance, ticket pocket',
    care: 'Dry clean only. Store with garment bags on wide cedar hangers. Air before bagging.',
  },
  {
    id: 'su-02',
    title: 'The Slate',
    category: 'suits',
    description: 'Cool grey wool in a slim silhouette. Effortless for boardroom or ceremony.',
    image: 'https://images.unsplash.com/photo-1593030761757-71fae45fa0e7?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: 'Super 110s Wool, Dormeuil cloth, mid-grey tone',
    craftsmanship: 'Half canvas, notch lapel, flap pockets, slim two-button front, double vent',
    care: 'Dry clean after 4–5 wears. Use a clothes brush to remove lint after each occasion.',
  },
  {
    id: 'su-03',
    title: 'The Ivory',
    category: 'suits',
    description: 'Cream linen tailored for the tropical heat of Accra without sacrificing refinement.',
    image: 'https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'portrait',
    fabric: 'Pure Irish linen, lightweight 180g/m², natural ivory',
    craftsmanship: 'Unstructured chest, natural shoulder, patch pockets, functional cuffs, hand-finished seams',
    care: 'Dry clean or press-clean. Light press on reverse with a damp cloth to refresh.',
  },
  {
    id: 'ac-01',
    title: 'Silk Grenadine',
    category: 'accessories',
    description: 'A hand-rolled silk grenadine tie in deep burgundy — the mark of considered dressing.',
    image: 'https://images.unsplash.com/photo-1553062407-98eeb64c6a62?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: '100% Mulberry Silk, open-weave grenadine, hand-rolled edges',
    craftsmanship: 'Hand-sewn keeper loop, weighted hem, rolled and slip-stitched finish',
    care: 'Spot clean or dry clean. Store rolled, not folded, to preserve the weave.',
  },
  {
    id: 'ac-02',
    title: 'Rhodium Cufflinks',
    category: 'accessories',
    description: 'Rhodium-plated cufflinks with a brushed finish. Understated. Permanent.',
    image: 'https://images.unsplash.com/photo-1624378515653-65e14f764f69?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: 'Rhodium-plated brass, brushed satin finish, T-bar fastening',
    craftsmanship: 'Precision cast, hand-polished face, hand-finished edges, secure swivel mechanism',
    care: 'Wipe with a soft polishing cloth. Store in the original pouch away from moisture.',
  },
  {
    id: 'ac-03',
    title: 'The Collar Bar',
    category: 'accessories',
    description: 'A sterling silver collar bar that elevates a white dress shirt to a statement.',
    image: 'https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: '925 sterling silver, mirror polish, spring clip mechanism',
    craftsmanship: 'Hand-polished, precision spring tension, designed for 1/4 inch collar button loops',
    care: 'Polish with a silver cloth as needed. Store in the velvet-lined case provided.',
  },
  {
    id: 'wa-01',
    title: 'The Chronograph',
    category: 'watches',
    description: 'A precision timepiece in brushed steel. Time is the one luxury you cannot replace.',
    image: 'https://images.unsplash.com/photo-1523275335684-37898b6baf30?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: '316L surgical stainless steel case, sapphire crystal glass, 42mm diameter',
    craftsmanship: 'Swiss ETA movement, 50m water resistance, exhibition caseback, screw-down crown',
    care: 'Wipe with a soft cloth. Service every 3–5 years. Avoid magnets and extreme temperatures.',
  },
  {
    id: 'wa-02',
    title: 'The Dress Watch',
    category: 'watches',
    description: 'Thin case, black alligator strap. The watch that disappears under a French cuff.',
    image: 'https://images.unsplash.com/photo-1547996996-0ea286e25c5d?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: '18K gold-plated case 7.9mm thin, genuine alligator leather strap, mineral crystal',
    craftsmanship: 'Swiss quartz movement, brushed and polished case finishing, tang buckle',
    care: 'Keep away from water. Store in the watch box. Strap conditions with leather balm annually.',
  },
  {
    id: 'wa-03',
    title: 'The Automatic',
    category: 'watches',
    description: 'Self-winding movement visible through a sapphire caseback. Worn by those who notice.',
    image: 'https://images.unsplash.com/photo-1526045431048-f857369baa09?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'square',
    fabric: 'PVD-coated stainless steel, anti-reflective sapphire crystal, 40mm case',
    craftsmanship: 'Swiss automatic movement, 48-hour power reserve, exhibition caseback, signed rotor',
    care: 'Wear daily for self-winding or use a watch winder. Service every 5 years.',
  },
  {
    id: 'ps-01',
    title: 'The Ivory Fold',
    category: 'pocket-squares',
    description: 'Hand-rolled ivory linen in a classic presidential fold. The final punctuation.',
    image: 'https://images.unsplash.com/photo-1589756823695-278bc923f962?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'landscape',
    fabric: 'Pure Irish linen, natural ivory, 33cm × 33cm',
    craftsmanship: 'Hand-rolled and hand-stitched edges, weighted corners for clean fold retention',
    care: 'Dry clean or hand wash cold. Press on reverse with a cool iron. Store flat.',
  },
  {
    id: 'ps-02',
    title: 'The Navy Peak',
    category: 'pocket-squares',
    description: 'Deep navy silk with a one-point peak. Geometric. Deliberate. Precise.',
    image: 'https://images.unsplash.com/photo-1598033129183-c4f50c736f10?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'landscape',
    fabric: 'Hand-rolled pure silk, Como Italy, deep navy, 32cm × 32cm',
    craftsmanship: 'Completely hand-rolled and hand-stitched, inherent weight for structured peak folds',
    care: 'Dry clean only. Store rolled loosely in a silk bag. Never press silk directly.',
  },
  {
    id: 'ps-03',
    title: 'The Pocket Puff',
    category: 'pocket-squares',
    description: 'White cotton in a relaxed puff fold — the effortless signal of a man at ease with craft.',
    image: 'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80&auto=format&fit=crop',
    aspectRatio: 'landscape',
    fabric: '100% Sea Island cotton, white, 35cm × 35cm, soft handfeel',
    craftsmanship: 'Hemstitched edges, fine cotton with natural body for the puff fold',
    care: 'Machine wash cold on gentle cycle. Tumble dry low or press with a warm iron.',
  },
]

export const CATEGORY_LABELS: Record<'all' | LookCategory, string> = {
  all: 'All',
  'alpha-man': 'Alpha Man',
  suits: 'Suits',
  accessories: 'Accessories',
  watches: 'Watches',
  'pocket-squares': 'Pocket Squares',
}

export const ALL_CATEGORIES: Array<'all' | LookCategory> = [
  'all',
  'alpha-man',
  'suits',
  'accessories',
  'watches',
  'pocket-squares',
]
